---
bigfix:
  content:
    Baselines:
      automation:
        trigger_file_path: baseline_plugin_run_now
        sites:
          - name: Updates for Windows Applications Extended
            auto_remediate: true
            offer_action: true
          # - name: Updates for Windows Applications
