---
name: Tag and Release

on:
  push:
    branches:
      - master
    paths:
      - "src/besapi/__init__.py"
      - "src/besapi/besapi.py"
      - ".github/workflows/tag_and_release.yaml"

jobs:
  release_new_tag:
    if: github.repository == 'jgstew/besapi'
    name: Tag and Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4
        with:
          fetch-tags: true

      - name: git pull tags
        run: git pull --tags

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12

      - name: Install requirements
        run: if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Read VERSION file
        id: getversion
        run: echo "version=$(python ./setup.py --version)" >> $GITHUB_OUTPUT

      # only make release if there is NOT a git tag for this version
      - name: "Check: package version has corresponding git tag"
        # this will prevent this from doing anything when run through ACT
        if: ${{ !env.ACT }} && contains(steps.getversion.outputs.version, '.')
        id: tagged
        shell: bash
        run: |
          if git show-ref --tags --verify --quiet -- "refs/tags/v${{ steps.getversion.outputs.version }}"; then
            echo "tagged=0" >> $GITHUB_OUTPUT
          else
            echo "tagged=1" >> $GITHUB_OUTPUT
          fi

      - name: echo tagged value
        run: |
          echo ${{ steps.tagged.outputs.tagged }}

      - name: Run pre-commit all-files
        if: steps.tagged.outputs.tagged == 1
        uses: pre-commit/action@v3.0.1
        with:
          extra_args: >-
            --color=always
            --all-files
            --hook-stage manual

      # wait for all other tests to succeed
      #   what if no other tests?
      - name: Wait for tests to succeed
        if: steps.tagged.outputs.tagged == 1
        uses: lewagon/wait-on-check-action@v1.3.1
        with:
          ref: master
          running-workflow-name: "Tag and Release"
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          wait-interval: 30

      - name: Install build tools
        if: steps.tagged.outputs.tagged == 1
        run: pip install setuptools wheel build

      - name: Run build
        if: steps.tagged.outputs.tagged == 1
        run: python3 -m build

      - name: Get Wheel File
        if: steps.tagged.outputs.tagged == 1
        id: getwheelfile
        shell: bash
        run: echo "wheelfile=$(find dist -type f -name '*.whl')" >> $GITHUB_OUTPUT

      - name: Automatically create github release
        if: steps.tagged.outputs.tagged == 1
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: v${{ steps.getversion.outputs.version }}
          prerelease: false
          files: |
            ${{ steps.getwheelfile.outputs.wheelfile }}

      - name: Publish distribution to PyPI
        if: steps.tagged.outputs.tagged == 1
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
